spring:
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
app:
  kafka:
    topic: ${KAFKA_TOPIC:timeline-events}
# spring:
#   kafka:
#     bootstrap-servers: localhost:9092
# app:
#   kafka:
#     topic: timeline-events
